### ISSUE TITLE
New release tag needed

### ISSUE THREAD

**Issue by hassaan4584** [tarbayev/OptiDiff#2]
While this is not an issue, it would be cool to have a tag `0.2.1` for the latest change that fixes issue with the support for swift package manager because without [this](https://github.com/tarbayev/OptiDiff/blob/72f6063ef8573421a459fea2aac5830400ff72e8/Sources/UI/UITableView%2BDiff.swift#L2) import statement, it doesnt compile when used with spm.

Thank you

**Comment by tarbayev** [comment]
@hassaan4584 Here you go!
https://github.com/tarbayev/OptiDiff/releases/tag/0.2.1
